### ISSUE TITLE
Starting the consumer without the schema registry

### ISSUE THREAD

**Issue by BenjaminDavison** [BetterCloud/kadmin#1]
Hi All,

We don't use the schema registry in our environments just yet, is there a way to ignore the registry url? 

Thanks,

Ben

**Comment by david-bc** [comment]
There is some convenience functionality that currently relies on the Schema Registry that won't work e.g. topic dropdown (I have plans to change that). So you will have to manually enter your topics in the producer/consumer.

But I just confirmed that the String, Int, and Long serializers/deserializers work without Schema Registry using Kafka 0.9.0.1 (`kafka_2.11-0.9.0.1-cp1.jar`) and zookeeper 3.4.6.

<img width="1147" alt="screen shot 2016-08-24 at 7 18 54 am" src="https://cloud.githubusercontent.com/assets/20439776/17928926/25089f20-69cb-11e6-9d31-a7683e0f21c4.png">

**Comment by BenjaminDavison** [comment]
Ah thanks! Didn't realise that you could still put in the topic name.
