### ISSUE TITLE
Messages are cut off

### ISSUE THREAD

**Issue by BenjaminDavison** [BetterCloud/kadmin#2]
I am consuming from a topic which outputs json, but I only get back the first character.

```
Key: ""
Consumed @12:37:25 PM
offset: 489704319
topic: fastly-logs
"{
```

I am using the stringdeserialiser 

Thanks,

Ben

**Comment by david-bc** [comment]
Can you give an example of the expected output?

**Comment by david-bc** [comment]
Reproduced locally, looking into it

**Comment by david-bc** [comment]
Confirmed fix locally. You need to pull the latest and rebuild or use `dist/shared-kafka-admin-micro-0.9.1.jar`

<img width="331" alt="screen shot 2016-08-24 at 8 16 37 am" src="https://cloud.githubusercontent.com/assets/20439776/17930250/39a47578-69d3-11e6-816e-5660eec26909.png">
