### ISSUE TITLE
Push dockerfile to docker hub

### ISSUE THREAD

**Issue by alexives** [BetterCloud/kadmin#8]
I really want to use this to do local development testing of kafka stream processors. Right now, we spin up our stream processor in docker-compose for testing and connect to it with kafkacat, but it would be pretty spiffy if this UI just spun up instead. I was thinking about pushing the docker container to our internal repository, but it'd be neat if you folks just had it in docker hub.

**Comment by david-bc** [comment]
Thanks for the suggestion. Let me talk to our devops team about pushing it to docker hub.

**Comment by hasnat** [comment]
I believe with the Dockerfile now we can create as an automated builds image on docker

**Comment by Hienphamthe** [comment]
Is there any already built image on dockerhub? that would be very nice.

**Comment by hasnat** [comment]
you can try one on https://hub.docker.com/r/hasnat/kadmin/

**Comment by Eirias** [comment]
> you can try one on https://hub.docker.com/r/hasnat/kadmin/

The image (hasnat/kadmin:latest)  is not working.

**Comment by hasnat** [comment]
> > you can try one on https://hub.docker.com/r/hasnat/kadmin/
> 
> The image (hasnat/kadmin:latest) is not working.

not working how? whats the error?

**Comment by Eirias** [comment]
Ah sorry i  just found [this closed issue](https://github.com/BetterCloud/kadmin/issues/10) and it solved my problem.

**Comment by pPanda-beta** [comment]
Hi @hasnat 
I think latest version of code is not there on the image. I need  #13 in the docker image please.

**Comment by hasnat** [comment]
@pPanda-beta updated fork changes and done rebuild for `hasnat/kadmin`
https://hub.docker.com/r/hasnat/kadmin/tags

**Comment by noelalonso** [comment]
Hi,
I need #15 in the docker image.
Thanks.

**Comment by david-bc** [comment]
@noelalonso could you verify the image from `bettercloud/kadmin:latest`? https://cloud.docker.com/u/bettercloud/repository/docker/bettercloud/kadmin

`$ docker-compose up` or `$ docker run -d -name kadmin bettercloud/kadmin`

**Comment by david-bc** [comment]
Fixed in https://github.com/BetterCloud/kadmin/pull/18
